### ISSUE TITLE
Error in yaml templates with !Ref tag

### ISSUE THREAD

**Issue by pit** [cfn-sphere/cfn-sphere#128]
Hello!
I'm  using pybuilder_aws_plugin plugin to upload yaml template to S3.
Inside this plugin uses your library cfn-sphere.

My template has following line:
`UserName: !Ref Username`

I run pybuilder with the following command:
`pyb upload_cfn_to_s3 -Pusername=test -X`

It fails with following exception:
```
[DEBUG] Executing subtask from pybuilder_aws_plugin.cfn_tasks
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pybuilder/cli.py", line 403, in main
    environments=options.environments, tasks=arguments)
  File "/Library/Python/2.7/site-packages/pybuilder/reactor.py", line 128, in build
    return self.build_execution_plan(tasks, execution_plan)
  File "/Library/Python/2.7/site-packages/pybuilder/reactor.py", line 170, in build_execution_plan
    reactor=self)
  File "/Library/Python/2.7/site-packages/pybuilder/execution.py", line 351, in execute_execution_plan
    summaries.append(self.execute_task(task, **keyword_arguments))
  File "/Library/Python/2.7/site-packages/pybuilder/execution.py", line 298, in execute_task
    task.execute(self.logger, keyword_arguments)
  File "/Library/Python/2.7/site-packages/pybuilder/execution.py", line 169, in execute
    executable.execute(argument_dict)
  File "/Library/Python/2.7/site-packages/pybuilder/execution.py", line 100, in execute
    self.callable(*arguments)
  File "/Users/peter/Library/Python/2.7/lib/python/site-packages/pybuilder_aws_plugin/cfn_tasks.py", line 24, in upload_cfn_to_s3
    template = FileLoader.get_cloudformation_template(filename, path)
  File "/Users/peter/Library/Python/2.7/lib/python/site-packages/cfn_sphere/file_loader.py", line 25, in get_cloudformation_template
    raise TemplateErrorException("Could not load file from {0}: {1}".format(url, e))
TemplateErrorException: Could not load file from iam-user.yaml: could not determine a constructor for the tag '!Ref'
  in "<unicode string>", line 14, column 17:
          UserName: !Ref Username
```

**Comment by marco-hoyer** [comment]
Hi, you're totally right. This new `!Function` syntax is somehow special for YAML. This should be fixed with the yaml parser to support it. This is related to #126.

**Comment by pit** [comment]
Aha, I see. Didn't find those ticket.
As far as I understand yaml library, you need to use yaml.constructor.Constructor to support such features.

**Comment by marco-hoyer** [comment]
done, will be included in the next release
