### ISSUE TITLE
Concurrency issue occurs when a stack is deleted while sync starts

### ISSUE THREAD

**Issue by marco-hoyer** [cfn-sphere/cfn-sphere#13]
If one starts a sync process while a stack is being deleted, an unexpected error occurs:

```
17.11.2015 17:07:03 ERROR cf: Failed with unexpected error
17.11.2015 17:07:03 ERROR cf: BotoServerError: 400 Bad Request
<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
  <Error>
    <Type>Sender</Type>
    <Code>ValidationError</Code>
    <Message>Stack with id my-stack does not exist</Message>
  </Error>
  <RequestId>3da680d3-8d45-11e5-9845-678f985fe5fb</RequestId>
</ErrorResponse>
Traceback (most recent call last):
  File "/data/home/foo/virtualenv27/bin/cf", line 69, in sync
    StackActionHandler(config).create_or_update_stacks()
  File "/data/home/foo/virtualenv27/lib/python2.7/site-packages/cfn_sphere/main.py", line 43, in create_or_update_stacks
    self.cfn.validate_stack_is_ready_for_updates(stack_name)
  File "/data/home/foo/virtualenv27/lib/python2.7/site-packages/cfn_sphere/aws/cloudformation/cfn_api.py", line 47, in validate_stack_is_ready_for_updates
    stack = self.get_stack(stack_name)
  File "/data/home/foo/virtualenv27/lib/python2.7/site-packages/cfn_sphere/aws/cloudformation/cfn_api.py", line 44, in get_stack
    return self.conn.describe_stacks(stack_name)[0]
  File "/data/home/foo/virtualenv27/lib/python2.7/site-packages/boto/cloudformation/connection.py", line 690, in describe_stacks
    return self.get_list('DescribeStacks', params, [('member', Stack)])
  File "/data/home/foo/virtualenv27/lib/python2.7/site-packages/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
BotoServerError: BotoServerError: 400 Bad Request
<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
  <Error>
    <Type>Sender</Type>
    <Code>ValidationError</Code>
    <Message>Stack with id my-stack does not exist</Message>
  </Error>
  <RequestId>3da680d3-8d45-11e5-9845-678f985fe5fb</RequestId>
</ErrorResponse>
```

**Comment by marco-hoyer** [comment]
This is due to the limiting nature of wrapping cloudformation api. Cfn-Sphere isn't able to implement transactional correctness. I improved the error message to simplify its interpretation.
