### ISSUE TITLE
Crash since version 0.1.35 because stack_config.working_dir is None

### ISSUE THREAD

**Issue by snordhausen** [cfn-sphere/cfn-sphere#135]
When running [aws-certificate-management](https://github.com/ImmobilienScout24/aws-certificate-management) (which makes direct Python-calls to cfn-sphere), I get the following backtrace:
```
Traceback (most recent call last):
  File "/home/snordhausen/venv/bin/aws-certificate-management", line 46, in <module>
    main()
  File "/home/snordhausen/venv/bin/aws-certificate-management", line 42, in main
    setup_certificate(args.domain, args.hosted_zone, args.region)
  File "/home/snordhausen/venv/lib/python2.7/site-packages/aws_certificate_management/__init__.py", line 17, in setup_certificate
    mail_bucket_name = create_ses_dns_records(domain, hosted_zone)
  File "/home/snordhausen/venv/lib/python2.7/site-packages/aws_certificate_management/configure_dns.py", line 95, in create_ses_dns_records
    stack_handler.create_or_update_stacks()
  File "/home/snordhausen/venv/lib/python2.7/site-packages/cfn_sphere/__init__.py", line 40, in create_or_update_stacks
    template = TemplateHandler.get_template(stack_config.template_url,stack_config.working_dir)
  File "/home/snordhausen/venv/lib/python2.7/site-packages/cfn_sphere/template/template_handler.py", line 10, in get_template
    additional_stack_description = "Config repo url: {0}".format(get_git_repository_remote_url(working_dir))
  File "/home/snordhausen/venv/lib/python2.7/site-packages/cfn_sphere/util.py", line 165, in get_git_repository_remote_url
    (head, tail) = os.path.split(working_dir)
  File "/home/snordhausen/venv/lib64/python2.7/posixpath.py", line 92, in split
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'

```
The problem disappears once I downgrade to version 0.1.34. It seems that https://github.com/cfn-sphere/cfn-sphere/commit/838294f3d1055f1b0d84014c6ff04086dd28e16e introduced the code that triggers the exception.

Also, the problem seems to only appear on hosts that need to go through an HTTP proxy to reach the internet.

Debugging showed that `stack_config.working_dir` is set to None `cfn_sphere/__init__.py`, both in version 0.1.34 and 0.1.36. Apparently, this used to be OK until recently. Can this be fixed by just adding a `if working_dir is None: return` at the right place in cfn-sphere (to avoid an exception) or is the value really necessary now?

**Comment by marco-hoyer** [comment]
Thx
