### ISSUE TITLE
 Connection reset by peer

### ISSUE THREAD

**Issue by julius-d** [cfn-sphere/cfn-sphere#148]
Hi!

in our build lane I got this stack trace when deploying:
```

[15:14:39]26.07.2017 15:14:39 INFO: Stack update started
[15:15:00]26.07.2017 15:15:00 INFO: xyz launchConfiguration: UPDATE_IN_PROGRESS (Requested update requires the creation of a new physical resource; hence creating one.)
[15:15:00]26.07.2017 15:15:00 INFO: xyz launchConfiguration: UPDATE_IN_PROGRESS (Resource creation Initiated)
[15:15:00]26.07.2017 15:15:00 INFO: xyz launchConfiguration: UPDATE_COMPLETE
[15:15:00]26.07.2017 15:15:00 INFO: xyz autoScalingGroup: UPDATE_IN_PROGRESS
[15:15:21]26.07.2017 15:15:21 INFO: xyz autoScalingGroup: UPDATE_IN_PROGRESS (Rolling update initiated. Terminating 2 obsolete instance(s) in batches of 1, while keeping at least 2 instance(s) in service. Waiting on resource signals with a timeout of PT15M when new instances are added to the autoscaling group.)
[15:15:21]26.07.2017 15:15:21 INFO: xyz autoScalingGroup: UPDATE_IN_PROGRESS (Temporarily setting autoscaling group MinSize and DesiredCapacity to 3.)
[15:16:13]26.07.2017 15:16:13 INFO: xyz autoScalingGroup: UPDATE_IN_PROGRESS (New instance(s) added to autoscaling group - Waiting on 1 resource signal(s) with a timeout of PT15M.)
[15:17:58]26.07.2017 15:17:58 ERROR: Failed with unexpected error
[15:17:58]26.07.2017 15:17:58 ERROR: [Errno 104] Connection reset by peer
[15:17:58]Traceback (most recent call last):
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/cli.py", line 78, in sync
[15:17:58]    StackActionHandler(config).create_or_update_stacks()
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/__init__.py", line 55, in create_or_update_stacks
[15:17:58]    self.cfn.update_stack(stack)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/aws/cfn.py", line 369, in update_stack
[15:17:58]    self.wait_for_stack_action_to_complete(stack.name, "update", stack.timeout)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/aws/cfn.py", line 420, in wait_for_stack_action_to_complete
[15:17:58]    timeout)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/aws/cfn.py", line 442, in wait_for_stack_event
[15:17:58]    events = self.get_stack_events(stack_name)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/util.py", line 144, in wrapper
[15:17:58]    return function(*args, **kwds)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/aws/cfn.py", line 125, in get_stack_events
[15:17:58]    return next(iter(pages))["StackEvents"]
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/paginate.py", line 102, in __iter__
[15:17:58]    response = self._make_request(current_kwargs)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/paginate.py", line 174, in _make_request
[15:17:58]    return self._method(**current_kwargs)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
[15:17:58]    return self._make_api_call(operation_name, kwargs)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/client.py", line 530, in _make_api_call
[15:17:58]    operation_model, request_dict)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
[15:17:58]    return self._send_request(request_dict, operation_model)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/endpoint.py", line 170, in _send_request
[15:17:58]    success_response, exception):
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/endpoint.py", line 249, in _needs_retry
[15:17:58]    caught_exception=caught_exception, request_dict=request_dict)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
[15:17:58]    return self._emit(event_name, kwargs)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
[15:17:58]    response = handler(**kwargs)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
[15:17:58]    if self._checker(attempts, response, caught_exception):
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
[15:17:58]    caught_exception)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
[15:17:58]    return self._checker(attempt_number, response, caught_exception)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
[15:17:58]    caught_exception)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
[15:17:58]    attempt_number, caught_exception)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
[15:17:58]    raise caught_exception
[15:17:58]error: [Errno 104] Connection reset by peer
[15:17:58]26.07.2017 15:17:58 INFO: Please report at https://github.com/cfn-sphere/cfn-sphere/issues!
[15:17:58]Process exited with code 1
[15:17:59]Process exited with code 1
[15:17:59]Step Command Line failed
```

but when looking in the cloudFormation website console all looks good for me.

**Comment by marco-hoyer** [comment]
Hi Julius,

Das sieht so aus als hätte es einen Verbindungsabbruch gegeben. Cfn-Sphere pollt auf die Stack Events und wartet auf das Ergebnis. Wenn dabei etwas schief geht, bricht can-sphere ab. Das Update läuft aber weiter. Hast du das öfter gesehen? Bisher ist mir das nicht wirklich untergekommen.

Beste Grüße
Marco


Hoyer, Marco
marco.hoyer@scout24.com<mailto:marco.hoyer@scout24.com>

--------------------------------------------------------------------------------------------------------
Immobilien Scout GmbH
Management: Dr. Michael Bütter, Dr. Thomas Schroeter
Chairman of the Supervisory Board: Gregory Ellis
Commercial Register: Local Court of Charlottenburg, HRB 69108
Place of Association: Berlin
--------------------------------------------------------------------------------------------------------

Am 26.07.2017 um 15:30 schrieb Julius Dannert <notifications@github.com<mailto:notifications@github.com>>:


Hi!

in our build lane I got this stack trace when deploying:


[15:14:39]26.07.2017 15:14:39 INFO: Stack update started
[15:15:00]26.07.2017 15:15:00 INFO: xyz launchConfiguration: UPDATE_IN_PROGRESS (Requested update requires the creation of a new physical resource; hence creating one.)
[15:15:00]26.07.2017 15:15:00 INFO: xyz launchConfiguration: UPDATE_IN_PROGRESS (Resource creation Initiated)
[15:15:00]26.07.2017 15:15:00 INFO: xyz launchConfiguration: UPDATE_COMPLETE
[15:15:00]26.07.2017 15:15:00 INFO: xyz autoScalingGroup: UPDATE_IN_PROGRESS
[15:15:21]26.07.2017 15:15:21 INFO: xyz autoScalingGroup: UPDATE_IN_PROGRESS (Rolling update initiated. Terminating 2 obsolete instance(s) in batches of 1, while keeping at least 2 instance(s) in service. Waiting on resource signals with a timeout of PT15M when new instances are added to the autoscaling group.)
[15:15:21]26.07.2017 15:15:21 INFO: xyz autoScalingGroup: UPDATE_IN_PROGRESS (Temporarily setting autoscaling group MinSize and DesiredCapacity to 3.)
[15:16:13]26.07.2017 15:16:13 INFO: xyz autoScalingGroup: UPDATE_IN_PROGRESS (New instance(s) added to autoscaling group - Waiting on 1 resource signal(s) with a timeout of PT15M.)
[15:17:58]26.07.2017 15:17:58 ERROR: Failed with unexpected error
[15:17:58]26.07.2017 15:17:58 ERROR: [Errno 104] Connection reset by peer
[15:17:58]Traceback (most recent call last):
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/cli.py", line 78, in sync
[15:17:58]    StackActionHandler(config).create_or_update_stacks()
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/__init__.py", line 55, in create_or_update_stacks
[15:17:58]    self.cfn.update_stack(stack)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/aws/cfn.py", line 369, in update_stack
[15:17:58]    self.wait_for_stack_action_to_complete(stack.name, "update", stack.timeout)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/aws/cfn.py", line 420, in wait_for_stack_action_to_complete
[15:17:58]    timeout)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/aws/cfn.py", line 442, in wait_for_stack_event
[15:17:58]    events = self.get_stack_events(stack_name)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/util.py", line 144, in wrapper
[15:17:58]    return function(*args, **kwds)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/aws/cfn.py", line 125, in get_stack_events
[15:17:58]    return next(iter(pages))["StackEvents"]
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/paginate.py", line 102, in __iter__
[15:17:58]    response = self._make_request(current_kwargs)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/paginate.py", line 174, in _make_request
[15:17:58]    return self._method(**current_kwargs)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
[15:17:58]    return self._make_api_call(operation_name, kwargs)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/client.py", line 530, in _make_api_call
[15:17:58]    operation_model, request_dict)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
[15:17:58]    return self._send_request(request_dict, operation_model)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/endpoint.py", line 170, in _send_request
[15:17:58]    success_response, exception):
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/endpoint.py", line 249, in _needs_retry
[15:17:58]    caught_exception=caught_exception, request_dict=request_dict)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
[15:17:58]    return self._emit(event_name, kwargs)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
[15:17:58]    response = handler(**kwargs)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
[15:17:58]    if self._checker(attempts, response, caught_exception):
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
[15:17:58]    caught_exception)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
[15:17:58]    return self._checker(attempt_number, response, caught_exception)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
[15:17:58]    caught_exception)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
[15:17:58]    attempt_number, caught_exception)
[15:17:58]  File "/opt/cfn-sphere/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
[15:17:58]    raise caught_exception
[15:17:58]error: [Errno 104] Connection reset by peer
[15:17:58]26.07.2017 15:17:58 INFO: Please report at https://github.com/cfn-sphere/cfn-sphere/issues!
[15:17:58]Process exited with code 1
[15:17:59]Process exited with code 1
[15:17:59]Step Command Line failed


but when looking in the cloudFormation website console all looks good for me.

**Comment by marco-hoyer** [comment]
Any news here? Please reopen if you still have problems here.
