### ISSUE TITLE
AWSTemplateFormatVersion: 2010-09-09 results in JSON serializable error

### ISSUE THREAD

**Issue by h1f1x** [cfn-sphere/cfn-sphere#165]
When a date is used in yaml, it results in an JSON serialization error.
Is this a bug in cfn-sphere or in the yaml file ?

See here:
```
$ cat t.yaml
AWSTemplateFormatVersion: 2010-09-09
Description: Example for BugReport

Resources:
  foo:
    Type: AWS::S3::Bucket
$ cf validate_template t.yaml
17.02.2018 11:17:00 ERROR: Failed with unexpected error
17.02.2018 11:17:00 ERROR: datetime.date(2010, 9, 9) is not JSON serializable
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cfn_sphere/cli.py", line 185, in validate_template
    CloudFormation().validate_template(template)
  File "/usr/local/lib/python2.7/site-packages/cfn_sphere/aws/cfn.py", line 522, in validate_template
    self.client.validate_template(TemplateBody=template.get_template_json())
  File "/usr/local/lib/python2.7/site-packages/cfn_sphere/template/__init__.py", line 44, in get_template_json
    return json.dumps(self.get_template_body_dict())
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.date(2010, 9, 9) is not JSON serializable
```

**Comment by marco-hoyer** [comment]
That's an interesting behavior. If you do not wrap the date with quotes it seems to be considered a date but actually it is not meant to be one.
