### ISSUE TITLE
InvalidGitRepositoryError

### ISSUE THREAD

**Issue by sambokai** [cfn-sphere/cfn-sphere#171]
```
This action will modify AWS infrastructure in account: *********
Are you sure? [y/N]: y
03.05.2018 14:57:24 ERROR: Failed with unexpected error
03.05.2018 14:57:24 ERROR: 'IterableList' object has no attribute 'origin'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cfn_sphere/util.py", line 191, in get_git_repository_remote_url
    repo = Repo(working_dir)
  File "/usr/local/lib/python3.6/site-packages/git/repo/base.py", line 167, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /Users/sbokai/Developer/Learning/AWS/BooksToRead_CF/stack

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cfn_sphere/cli.py", line 80, in sync
    StackActionHandler(config).create_or_update_stacks()
  File "/usr/local/lib/python3.6/site-packages/cfn_sphere/__init__.py", line 39, in create_or_update_stacks
    template = TemplateHandler.get_template(stack_config.template_url, stack_config.working_dir)
  File "/usr/local/lib/python3.6/site-packages/cfn_sphere/template/template_handler.py", line 10, in get_template
    additional_stack_description = "Config repo url: {0}".format(get_git_repository_remote_url(working_dir))
  File "/usr/local/lib/python3.6/site-packages/cfn_sphere/util.py", line 196, in get_git_repository_remote_url
    return get_git_repository_remote_url(head)
  File "/usr/local/lib/python3.6/site-packages/cfn_sphere/util.py", line 192, in get_git_repository_remote_url
    return repo.remotes.origin.url
  File "/usr/local/lib/python3.6/site-packages/git/util.py", line 894, in __getattr__
    return list.__getattribute__(self, attr)
AttributeError: 'IterableList' object has no attribute 'origin'
03.05.2018 14:57:24 INFO: Please report at https://github.com/cfn-sphere/cfn-sphere/issues!
```

Any ideas?

**Comment by sambokai** [comment]
It was a messy python issue.

**Comment by sambokai** [comment]
Sorry for closing and opening that often. I was trying to exclude any reasons for failure i could think of. The state right now is that i uninstalled all the python installations (except the system ones) i had, and reinstalled python2. Still getting the error

**Comment by marco-hoyer** [comment]
Hi @sambokai, thanks for reporting. Which git version are you using? I will try to reproduce this error.

**Comment by sambokai** [comment]
I use git version 2.17.0

**Comment by marco-hoyer** [comment]
I was not able to reproduce and did not hear from anyone else having this problem. Please reopen if it is still an issue.

**Comment by mapu77** [comment]
Seems related to #189 
If the stack is defined in a git repository without remote defined, the sync doesn't start.
