### ISSUE TITLE
More efficient way to check whether to create or update a stack

### ISSUE THREAD

**Issue by MeiSign** [cfn-sphere/cfn-sphere#183]
**Problem**
If you have an AWS account with a lot of cloudformation stacks you can run into AWS API throttling issues while updating a stack with cfn-sphere. 

The create_or_update_stacks function is getting a list of all stacks to determine whether new stacks need to be created or existing stacks should be updated.

https://github.com/cfn-sphere/cfn-sphere/blob/master/src/main/python/cfn_sphere/__init__.py#L21

The api throttling looks like this:

```
[15:03:14]	[Step 12/16] 24.05.2019 15:03:41 ERROR: An error occurred (Throttling) when calling the DescribeStacks operation (reached max retries: 4): Rate exceeded
[15:03:14]	[Step 12/16] Traceback (most recent call last):
[15:03:14]	[Step 12/16]   File "/opt/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/cli.py", line 81, in sync
[15:03:14]	[Step 12/16]     StackActionHandler(config).create_or_update_stacks()
[15:03:14]	[Step 12/16]   File "/opt/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/__init__.py", line 54, in create_or_update_stacks
[15:03:14]	[Step 12/16]     self.cfn.validate_stack_is_ready_for_action(stack)
```

**Possible solution**
Instead of getting all stacks and comparing the desired stacks with existing stacks, one could do a describe call for each desired stack to determine whether it exists already.

**Comment by marco-hoyer** [comment]
This sounds like a good plan. I will have a look soon.
