### ISSUE TITLE
InvalidGitRepositoryError using cf  sync

### ISSUE THREAD

**Issue by kunwar-aditya** [cfn-sphere/cfn-sphere#193]
I am issuing a simple command  `cf sync box-stacks.yaml` and this gives me the below error -

```
This action will modify AWS infrastructure in account: <account-name>
Are you sure? [y/N]: y
INFO: Will process stacks in the following order: stack-one, stack-two, stack-three
ERROR: Failed with unexpected error
ERROR: 'IterableList' object has no attribute 'origin'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cfn_sphere/util.py", line 191, in get_git_repository_remote_url
    repo = Repo(working_dir)
  File "/usr/local/lib/python3.10/site-packages/git/repo/base.py", line 266, in __init__
    self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
  File "/usr/local/lib/python3.10/site-packages/git/repo/base.py", line 347, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cfn_sphere/cli.py", line 90, in sync
    StackActionHandler(config).create_or_update_stacks()
  File "/usr/local/lib/python3.10/site-packages/cfn_sphere/__init__.py", line 37, in create_or_update_stacks
    template = TemplateHandler.get_template(stack_config.template_url, stack_config.working_dir)
  File "/usr/local/lib/python3.10/site-packages/cfn_sphere/template/template_handler.py", line 10, in get_template
    additional_stack_description = "Config repo url: {0}".format(get_git_repository_remote_url(working_dir))
  File "/usr/local/lib/python3.10/site-packages/cfn_sphere/util.py", line 196, in get_git_repository_remote_url
    return get_git_repository_remote_url(head)
  File "/usr/local/lib/python3.10/site-packages/cfn_sphere/util.py", line 192, in get_git_repository_remote_url
    return repo.remotes.origin.url
  File "/usr/local/lib/python3.10/site-packages/git/util.py", line 1083, in __getattr__
    return list.__getattribute__(self, attr)
AttributeError: 'IterableList' object has no attribute 'origin'
22.12.2022 17:19:17 INFO: Please report at https://github.com/cfn-sphere/cfn-sphere/issues!
```

No idea what to look into next. Any pointers?

**Comment by pluralistix** [comment]
Here is "the pointer" https://github.com/cfn-sphere/cfn-sphere/issues/189 you were asking for...

You could simply

```
git remote add origin ""
```

Or, if you do have git repos without remotes often times and do not want to forget about :point_up: do

```
sed -i '/get_git_repository_remote_url/d' $( $(sed -r -n 's;^#!(.*);\1;p' $(command -v cf)) -c 'import cfn_sphere.template.template_handler as _; print(_.__file__)' )
```

and keep forgetting about that instead :smile:

**Comment by kunwar-aditya** [comment]
Thank you @pluralistix !!
