### ISSUE TITLE
Properly Handle BotoServerErrors

### ISSUE THREAD

**Issue by jbspeakr** [cfn-sphere/cfn-sphere#29]
From time to time (e.g. when my Stack API Limits exceeded), I get BotoServerError like this one:

```
18.12.2015 14:58:25 ERROR cf: Failed with unexpected error
18.12.2015 14:58:25 ERROR cf: BotoServerError: 400 Bad Request
<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
  <Error>
    <Type>Sender</Type>
    <Code>Throttling</Code>
    <Message>Rate exceeded</Message>
  </Error>
  <RequestId>687fa3e7-a58f-11e5-#####-#####</RequestId>
</ErrorResponse>
Traceback (most recent call last):
  File "/usr/local/bin/cf", line 68, in sync
    StackActionHandler(config).create_or_update_stacks()
  File "/usr/local/lib/python2.7/site-packages/cfn_sphere/main.py", line 37, in create_or_update_stacks
    parameters = self.parameter_resolver.resolve_parameter_values(stack_config.parameters, stack_name)
  File "/usr/local/lib/python2.7/site-packages/cfn_sphere/resolver/parameter_resolver.py", line 101, in resolve_parameter_values
    parameters[key] = str(self.get_output_value(referenced_stack + '.' + output_name))
  File "/usr/local/lib/python2.7/site-packages/cfn_sphere/resolver/parameter_resolver.py", line 53, in get_output_value
    artifacts = self.get_stack_outputs()
  File "/usr/local/lib/python2.7/site-packages/cfn_sphere/resolver/parameter_resolver.py", line 40, in get_stack_outputs
    stacks = self.cfn.get_stacks()
  File "/usr/local/lib/python2.7/site-packages/cfn_sphere/aws/cloudformation/cfn_api.py", line 26, in get_stacks
    response = self.conn.describe_stacks()
  File "/usr/local/lib/python2.7/site-packages/boto/cloudformation/connection.py", line 690, in describe_stacks
    return self.get_list('DescribeStacks', params, [('member', Stack)])
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
BotoServerError: BotoServerError: 400 Bad Request
<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
  <Error>
    <Type>Sender</Type>
    <Code>Throttling</Code>
    <Message>Rate exceeded</Message>
  </Error>
  <RequestId>687fa3e7-a58f-11e5-#####-########</RequestId>
</ErrorResponse>
```

In my eyes, this and similar exceptions should be catched and translated into proper error messages.

**Comment by marco-hoyer** [comment]
Uhh, a throttling exception. You are absolutely right.
