### ISSUE TITLE
Yaml Parser Exceptions cause stack traces

### ISSUE THREAD

**Issue by marco-hoyer** [cfn-sphere/cfn-sphere#33]
```
22.12.2015 13:19:41 ERROR cf: Failed with unexpected error
22.12.2015 13:19:41 ERROR cf: while parsing a block mapping
  in "<string>", line 157, column 11:
              GF_SECURITY_ADMIN_PASSWORD: "|Re ...
              ^
expected <block end>, but found '<block sequence start>'
  in "<string>", line 161, column 15:
                  - |GetAtt|database|Endpoint.Address
                  ^
Traceback (most recent call last):
  File "/usr/local/bin/cf", line 68, in sync
    StackActionHandler(config).create_or_update_stacks()
  File "/usr/local/lib/python2.7/site-packages/cfn_sphere/main.py", line 34, in create_or_update_stacks
    template = CloudFormationTemplateLoader.get_template_from_url(template_url, working_dir)
  File "/usr/local/lib/python2.7/site-packages/cfn_sphere/aws/cloudformation/template_loader.py", line 15, in get_template_from_url
    return CloudFormationTemplate(body_dict=cls._fs_get_template(url, working_dir), name=os.path.basename(url))
  File "/usr/local/lib/python2.7/site-packages/cfn_sphere/aws/cloudformation/template_loader.py", line 33, in _fs_get_template
    return yaml.load(template_file.read())
  File "/usr/local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python2.7/site-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
ParserError: while parsing a block mapping
  in "<string>", line 157, column 11:
              GF_SECURITY_ADMIN_PASSWORD: "|Re ...
              ^
expected <block end>, but found '<block sequence start>'
  in "<string>", line 161, column 15:
                  - |GetAtt|database|Endpoint.Address
                  ^
```

**Comment by marco-hoyer** [comment]
already fixed. this happened with an old version
