### ISSUE TITLE
Error loading json from s3

### ISSUE THREAD

**Issue by marco-hoyer** [cfn-sphere/cfn-sphere#57]
Cfn-Sphere fails loading files from s3 when used with python 3.5.1.

```
02.03.2016 14:44:53 ERROR: Could not load file from s3://cfn-templates/infrastructure/bucket.json: the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "/data/home/user/virtualenv35/lib/python3.5/site-packages/cfn_sphere/file_loader.py", line 44, in _s3_get_file
    return json.loads(s3.get_contents_from_url(url))
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/user/virtualenv35/lib/python3.5/site-packages/cfn_sphere/cli.py", line 77, in sync
    StackActionHandler(config).create_or_update_stacks()
  File "/data/home/user/virtualenv35/lib/python3.5/site-packages/cfn_sphere/__init__.py", line 33, in create_or_update_stacks
    raw_template = FileLoader.get_file_from_url(stack_config.template_url, stack_config.working_dir)
  File "/data/home/user/virtualenv35/lib/python3.5/site-packages/cfn_sphere/file_loader.py", line 15, in get_file_from_url
    return CloudFormationTemplate(body_dict=cls._s3_get_file(url), name=os.path.basename(url))
  File "/data/home/user/virtualenv35/lib/python3.5/site-packages/cfn_sphere/file_loader.py", line 50, in _s3_get_file
    raise TemplateErrorException("Could not load file from {0}: {1}".format(url, e))
cfn_sphere.exceptions.TemplateErrorException: Could not load file from s3://cfn-templates/infrastructure/bucket.json: the JSON object must be str, not 'bytes'
```

**Comment by marco-hoyer** [comment]
both key.get_contents_as_string() returns bytes if no encoding is defined and is used with python3. This seems to be new behavior?! With explicit encoding set we should be safe here.
