### ISSUE TITLE
Remove support for sns subscription

### ISSUE THREAD

**Issue by nmohaupt** [cfn-sphere/cfn-sphere#70]
The build-in support for sns-subscription does not work properly. During an update the following error occured:

```
[Step 1/1] 29.03.2016 14:07:30 INFO: Subscribing queue psx-test-queues-realtorInputQueue-1LEEAJ8KKE1D4 to topic <XYZ> in eu-west-1
[14:07:30][Step 1/1] 29.03.2016 14:07:30 ERROR: Failed with unexpected error
[14:07:30][Step 1/1] 29.03.2016 14:07:30 ERROR: 'Sid'
[14:07:30][Step 1/1] Traceback (most recent call last):
[14:07:30][Step 1/1]   File "/opt/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/cli.py", line 74, in sync
[14:07:30][Step 1/1]     StackActionHandler(config).create_or_update_stacks()
[14:07:30][Step 1/1]   File "/opt/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/__init__.py", line 56, in create_or_update_stacks
[14:07:30][Step 1/1]     CustomResourceHandler.process_post_resources(stack)
[14:07:30][Step 1/1]   File "/opt/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/custom_resources.py", line 15, in process_post_resources
[14:07:30][Step 1/1]     cls.handle_sns_subscription(resource_description, stack)
[14:07:30][Step 1/1]   File "/opt/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/custom_resources.py", line 35, in handle_sns_subscription
[14:07:30][Step 1/1]     sns_conn.subscribe_sqs_queue(topic_arn, queue)
[14:07:30][Step 1/1]   File "/opt/cfn-sphere/lib/python2.7/site-packages/boto/sns/connection.py", line 361, in subscribe_sqs_queue
[14:07:30][Step 1/1]     if s['Sid'] == sid:
```

As the subscription is better handeled via cloudformation custom resources the support should be removed.

If we don't remove it, it should be fixed.

**Comment by marco-hoyer** [comment]
Yes, you're absolutely right. This is actually in use but I'm on it.

**Comment by marco-hoyer** [comment]
code removed with https://github.com/cfn-sphere/cfn-sphere/commit/3bd9c60c57c10cb229904f38b5c6ae1e6cb0604d

**Comment by marco-hoyer** [comment]
As this feature isn't used that much, I decided to raise an Exception warning the user that the PostCustomResource is not handled by cfn-sphere any more to make sure people recognize it.
