### ISSUE TITLE
Python 3.5

### ISSUE THREAD

**Issue by esc** [cfn-sphere/cfn-sphere#8]
I tried it with python 3.5:

```
Traceback (most recent call last):
  File "/home/esc/anaconda/envs/cf/bin/cf", line 7, in <module>
    from cfn_sphere.util import convert_file, get_logger, get_message_from_boto_server_error, convert_dict_to_json_string, \
  File "/home/esc/anaconda/envs/cf/lib/python3.5/site-packages/cfn_sphere/util.py", line 4, in <module>
    import urllib2
ImportError: No module named 'urllib2'
```

**Comment by marco-hoyer** [comment]
Hi, can you please verify this being fixed using the latest version?

**Comment by esc** [comment]
Looks good to me. Tried all unit-tests in a py35 env and it worked. thx!
